name = "TFL"
author = "Alice C"
version = "1.2.1"
description = "A special modpack made for TheForgedLand SMP"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98dfdd65f421c44e7b4f849351bba36e6516c494003d518e2da6a74af3d6e639"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
unsup = "0.2.0"
