name = "TheForgedLand"
author = "Alice C."
version = "2.1.2"
description = "A special modpack made for TheForgedLand SMP 2nd Season"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "524873786ac0690a81a18c22127401bfb28fa1c4da0cf6434b92a5a7cdcb6f07"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
unsup = "0.2.0"
