name = "TFL"
author = "Alice C"
version = "1.2.1"
description = "A special modpack made for TheForgedLand SMP"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd8db4ecf989384f44b7dc0ea51599727bb474012d18c4c85c10817a767272d7"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
unsup = "0.2.0"
