name = "TFL"
author = "Alice C"
version = "1.2.1"
description = "A special modpack made for TheForgedLand SMP"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f98b071443269e28f33b044736212b4baca192b96aa4b4ce43dc02e24774855f"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
unsup = "0.2.0"
