name = "TheForgedLand"
author = "Alice C."
version = "2.1.2"
description = "A special modpack made for TheForgedLand SMP 2nd Season"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8e7694de350216ba5a4ba1d5b1f39774df909ac13de18fae50576756d4a813b"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
unsup = "0.2.0"
