name = "TFL"
author = "Alice C"
version = "1.2.1"
description = "A special modpack made for TheForgedLand SMP"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73bd97814d7478661af4e491d3b693f6380038211d8b75d27bf96887d8fb5eab"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
unsup = "0.2.0"
