// priority: 0

console.info('Diet tags Reloaded')


ServerEvents.tags('item', event => {
// Get the #forge:cobblestone tag collection and add Diamond Ore to it
// event.get('forge:cobblestone').add('minecraft:diamond_ore')
	event.get("kitsune:berries")
		.add("farmersdelight:sweet_berry_cheesecake_slice")
		.add("farmersdelight:sweet_berry_cookie")
		.add("farmersdelight:glow_berry_custard")
		.add("expandeddelight:sweet_berry_jelly_sandwich")
		.add("expandeddelight:glow_berry_jelly_sandwich")
		.add("expandeddelight:berry_sweet_roll")
		.add("expandeddelight:glow_berry_sweet_roll")
		.add("expandeddelight:sweet_berry_juice")
		.add("expandeddelight:glow_berry_juice")
		.add("expandeddelight:sweet_berry_jelly")
		.add("expandeddelight:glow_berry_jelly")
		.add("create:chocolate_glazed_berries")
		.add("byg:blueberries")
		.add("byg:blueberry_pie")
		.add("byg:nightshade_berries")
		.add("byg:nightshade_berry_pie")
		.add("byg:crimson_berries")
		.add("byg:crimson_berry_pie")
		.add("twilightforest:torchberries")

	event.get("origins-plus-plus:sweets")
		.add("farmersdelight:hot_cocoa")
		.add("farmersdelight:cake_slice")
		.add("farmersdelight:apple_pie_slice")
		.add("farmersdelight:chocolate_pie_slice")
		.add("farmersdelight:honey_cookie")
		.add("farmersdelight:melon_popsicle")
		.add("expandeddelight:peanut_butter_honey_sandwich")
		.add("expandeddelight:sweet_roll")
		.add("expandeddelight:chocolate_cookie")
		.add("expandeddelight:sugar_cookie")
		.add("#kitsune:berries")
		.add("brewinandchewin:cocoa_fudge")
		.add("#c:fruits")
		.add("byg:green_apple_pie")
		.add("byg:cooked_joshua_fruit")
		.add("create:bar_of_chocolate")
		.add("create:sweet_roll")
		.add("create:honeyed_apple")
		.add("ecologics:prickly_pear")
		.add("ecologics:cooked_prickly_pear")
		.add("delightfulcreators:incomplete_apple_pie")
		.add("delightfulcreators:incomplete_pumpkin_pie")
		.add("delightfulcreators:incomplete_sweet_berry_cheesecake")
		.add("delightfulcreators:incomplete_rose_hip_pie")
		.add("delightfulcreators:pumpkin_pie_slice")
		.add("delightfulcreators:incomplete_coffee_cake")
		.add("delightfulcreators:coffee_cake_sponge")
		.add("delightfulcreators:coffee_cake_coating")
		.add("twilightforest:experiment_115")


	event.get("origins-plus-plus:raw_fish")
		.add("#c:raw_fishes")
		.add("culturaldelights:squid")
		.add("culturaldelights:glow_squid")
		.add("culturaldelights:raw_calamari")
		.add("culturaldelights:pufferfish_roll")
		.add("culturaldelights:tropical_roll")
		.add("culturaldelights:rice_ball")
		.add("culturaldelights:calamari_roll")
		.add("ecologics:crab_meat")
		.add("ecologics:tropical_stew")
		.add("farmersdelight:salmon_roll")
		.add("farmersdelight:cod_roll")


	event.get("origins-plus-plus:raw_meat")
		.add("#origins-plus-plus:raw_fish")
		.add("#brewinandchewin:raw_meats")
		.add("farmersdelight:ham")
		.add("nethersdelight:hoglin_loin")
		.add("twilightforest:raw_venison")
		.add("twilightforest:raw_meef")


	event.get("origins:meat")
		.add("#origins-plus-plus:raw_meat")
		.add("#c:cooked_fishes")
		.add("#c:cooked_beef")
		.add("#c:cooked_pork")
		.add("#c:cooked_chicken")
		.add("farmersdelight:smoked_ham")
		.add("farmersdelight:barbecue_stick")
		.add("farmersdelight:chicken_sandwich")
		.add("farmersdelight:hamburger")
		.add("farmersdelight:bacon_sandwich")
		.add("farmersdelight:mutton_wrap")
		.add("farmersdelight:stuffed_potato")
		.add("farmersdelight:bone_broth")
		.add("farmersdelight:beef_stew")
		.add("farmersdelight:chicken_soup")
		.add("farmersdelight:fish_stew")
		.add("farmersdelight:baked_cod_stew")
		.add("farmersdelight:noodle_soup")
		.add("farmersdelight:bacon_and_eggs")
		.add("farmersdelight:pasta_with_meatballs")
		.add("farmersdelight:pasta_with_mutton_chop")
		.add("farmersdelight:roasted_mutton_chops")
		.add("farmersdelight:dog_food")
		.add("farmersdelight:roast_chicken")
		.add("farmersdelight:honey_glazed_ham")
		.add("farmersdelight:shepherds_pie")
		.add("farmersdelight:steak_and_potatoes")
		.add("brewinandchewin:jerky")
		.add("brewinandchewin:kippers")
		.add("brewinandchewin:fiery_fondue")
		.add("culturaldelights:beef_burrito")
		.add("culturaldelights:mutton_sandwich")
		.add("culturaldelights:chicken_taco")
		.add("culturaldelights:spicy_curry")
		.add("culturaldelights:pork_wrap")
		.add("culturaldelights:fish_taco")
		.add("culturaldelights:chicken_roll")
		.add("culturaldelights:chicken_roll")
		.add("culturaldelights:chicken_roll_slice")
		.add("culturaldelights:cooked_squid")
		.add("culturaldelights:cooked_calamari")
		.add("nethersdelight:plate_of_stuffed_hoglin_snout")
		.add("nethersdelight:plate_of_stuffed_hoglin_ham")
		.add("nethersdelight:plate_of_stuffed_hoglin_roast")
		.add("nethersdelight:hoglin_sirloin")
		.add("nethersdelight:strider_slice")
		.add("nethersdelight:ground_strider")
		.add("nethersdelight:hoglin_ear")
		.add("nethersdelight:warped_moldy_meat")
		.add("nethersdelight:grilled_strider")
		.add("nethersdelight:strider_moss_stew")
		.add("nethersdelight:nether_skewer")
		.add("twilightforest:cooked_venison")
		.add("twilightforest:hydra_chop")
		.add("twilightforest:cooked_meef")
		.add("twilightforest:meef_stroganoff")


	// Get the #forge:cobblestone tag collection and remove Mossy Cobblestone from it
	// event.get('forge:cobblestone').remove('minecraft:mossy_cobblestone')
})